version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "8081:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - api1
      - api2

  api1:
    image: myapi:latest
    build: 
      context: api/
      dockerfile: Dockerfile
    container_name: api1
    restart: unless-stopped
    networks:
      - internal_network

    #expose:
     # - "5000"


  api2:
    image: myapi:latest
    build: 
      context: api/
      dockerfile: Dockerfile
    container_name: api2
    restart: unless-stopped
    networks:
      - internal_network
    #expose:
     # - "5000"
     #
networks:
  internal_network:
    driver: bridge

